mutation CreateClient($input: insertclientsInput!) {
  clients(insert: $input) {
    customer_name
    customer_address
    customer_contact_name
    customer_contact_number
    size
    license_and_registration
    credit_limit
    currency_for_credit_limit
    country_of_incorporation
    created_at
    updated_at
    __typename
  }
}
