mutation CreateLicenseForSupplier($input: insertlicense_and_registrationInput!) {
  license_and_registration(insert: $input) {
    id
    supplier_id
    license_registration_fileobject_id
    __typename
  }
} 