query GetSuppliersWithCursor($cursor: String) {
  suppliers(limit: 10, after: $cursor, orderBy: {created_at: desc}) {
    id
    unique_id
    supplier_name
    supplier_address
    supplier_contact_name
    supplier_contact_number
    supplier_contact_email
    operational_contact_name
    operational_contact_number
    operational_contact_email
    size
    credit_limit
    currency_for_credit_limit
    country_of_incorporation
    insured
    blacklisted
    created_at
    updated_at
    license_and_registration {
      id
      supplier_id
      license_registration_fileobject_id
      created_at
      updated_at
      __typename
    }
    __typename
  }
  suppliers_cursor
}